name: CI

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  php:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build the docker image
        run: |
          docker build -t omegaup/hook_tools .

      - name: Test
        run: |
          docker run \
            --rm \
            --user "$(id -u):$(id -g)" \
            --volume "${PWD}:/src" \
            --entrypoint /bin/bash \
            omegaup/hook_tools \
            /src/test.sh
