name: Build containers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@43ed073f5c1445ca8b80d920ce2f8fa550ae4e8d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 1.0.0

      - name: Build docker containers
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
              docker login "--username=${{ secrets.DOCKER_USERNAME }}" --password-stdin

          docker buildx build \
            --push \
            --platform=linux/amd64,linux/arm64/v8 \
            --tag=${{ steps.bump-version.outputs.tag }} \
            .
